name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 15]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup WeasyPrint
        run: pip3 install WeasyPrint
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run build
        run: yarn run build
      - name: Upload example builds
        uses: actions/upload-artifact@v2
        with:
          name: Example Output
          path: examples/**/dist/*
